name: weather_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  dev: ^1.0.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  geolocator: ^11.0.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  weather: ^3.1.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  freezed: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/
  


